### ISSUE TITLE
Error While Reading the Mesh

### ISSUE THREAD

**Issue by SibghatUllah13** [Rad-hi/3D-Rendering-Desktop-App#4]
I am getting the following errors (please see the image):

![Screenshot from 2023-02-22 14-08-38](https://user-images.githubusercontent.com/16798842/220628685-f514af33-fc10-4c92-add3-588cf31227db.png)

Do you know how to fix it?

Best Wishes,
Sibghat.

**Comment by Rad-hi** [comment]
Hello Sibghat,
Are using one of the files I provide in the Objects folder, or is this a new one you found/made ?
The issue is that this file has a line with a missing vertex. 
Please provide me with the file, and then I'll reproduce the bug and fix it appropriately (I know where the bug is, I just want to make sure I provide a proper fix, not a patch)

**Comment by SibghatUllah13** [comment]
Hi,

I made a new obj file myself, which I wish to render.

Here is the [link](https://drive.google.com/file/d/1tUNc1bS33fn2awewZ-VYH573GcfE-_Ry/view?usp=share_link) to the file.

**Comment by Rad-hi** [comment]
Hello, 
So here's how a drawable face looks like in:
- Objects/Tank.obj: `f 78/86/66 79/87/67 80/88/68`
- mesh-2.obj (your file): `f 1 2 20 19`
In your case, I don't really know how the faces are described.

The code is crashing because i'm using a split on the char `/` to get the triangles that constitute a face, but since you don't have any `/` in your file, you end up with empty strings as input to the call to `int()` in file `obj_files_handler.py`. 

Maybe study the format of the file you're supplying and modify the parsing code appropriately to comply with this format.
