### ISSUE TITLE
can't see outside faces

### ISSUE THREAD

**Issue by MarioGavran** [Rad-hi/3D-Rendering-Desktop-App#5]
I don't know if this is meant to bi like this or if I have something wrong, but it is clear when I open a simple cylinder .obj file (made in blender) that I cant see outside faces, but instead I see only inside wall of the cylinder. It actually look the same with the MaleLow.obj file, it is just more complex model and can't be easily noticed.

here are some screenshots with different rotations:
![Screenshot from 2023-12-22 08-02-41](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/9138ac39-3910-47a6-8bc4-9fbfd07d873e)
![Screenshot from 2023-12-22 08-02-16](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/e38f2b70-2c25-4a59-9108-a4e322196549)
![Screenshot from 2023-12-22 08-01-59](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/1a2cf890-ffe6-46a9-92ba-245a1707214e)

is there a way to make only the front faces visible? Is it difficult to modify the code to not render faces in the back.. or to render front faces over those in the back.. I don't actually understand the algorithm behind rendering 

this is what it should look like:
![Screenshot from 2023-12-22 08-11-31](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/e5cdacf4-7f46-4cfe-a2d7-5ee9fe06ded8)

**Comment by Rad-hi** [comment]
Hello, and thank you for your interest in my project !
So yeah, that's an issue I am aware of and never came to fix it.

Basically, the reason that's happening is that we are drawing points in the order that we read them from the `.obj` file. The issue with that is that we might be drawing points that are supposed to be occluded by another surface on top of that surface, just because these points were read later from the file.

One way to solve this is through implementing an algorithm called z-buffering, which would allow us to know which points are occluding each other, and only draw the ones that are “closest” to the camera/pov. (basically closer to the screen.)

Achieving this without understanding the rendering might be a bit tricky, but the cool thing is that the algorithm isn't that hard to understand, so I highly recommend taking a deeper look into it and giving it a shot !

I hope I answered your question clearly.

**Comment by MarioGavran** [comment]
I see now that if I change the 'transform' and 'geometry' options in Blender while exporting the model, some of the lines and surfaces are rendered better or worst, but I can't find the right combination. 
I think this has something to do with the way the faces are drawn.. probably their order.. because if I use 'no fill' I can see all the lines, like expected, like the object is transparent


edit:
i wrote this comment before you replied, but for some reason I never posted it so when I came back to post it, I didn't see your answer 
okay, I'll see what I can do, thanks

**Comment by MarioGavran** [comment]
I am now sorting the faces before rendering so that the furthest faces are rendered first and closest are rendered last. but, I don't know what would be the reference point.. where is the "camera" ?. 

Is the reference just one fixed point and the object is transformed relative to that or is the reference moving as the object is rotated. Now I just use some far away xyz point (eg. (20, 0, 10)) but it still isn't how it should be.

The problem, as I understand it so far, is that the whole polygons are rendered one by one. Usually the points would be rendered so it is easy to find the 'depth' of each point. Here,  it is hard to know which polygon is further than some other polygon(eg. by finding center of polygon). For example, in my cylinder model, some of the square polygons that make the inside of the cylinder would be considered closer than one of the larger polygons at the top of the cylinder (those shaped like a half-moon) and those would be rendered over the large half-moon-shaped polygon, thus making it look like the cylinder is open

![Screenshot from 2023-12-23 07-28-01](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/12ce6f96-8c87-459d-a77c-81b6bc85e630)

**Comment by MarioGavran** [comment]
I found another solution for my project (openGL in tkinter frame), so I wont be working on this for now.

**Comment by MarioGavran** [comment]
I'm back already, lol .. this project seems to be lot easier to work on than the other one I found.

I am starting to get somewhere with reordering the faces.. the MaleLow.obj now looks pretty good .. but only when viewed from the fron.. when I rotate it it still renders front over the back.. I don't understand why 
![Recording 2023-12-25 at 12 53 37](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/25e1fc0b-8e73-4a20-b5fc-ee5f88243d71)
![Recording 2023-12-25 at 12 59 00](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/54660960-4e6b-48b3-bf5c-e3126fe5c56f)

**Comment by MarioGavran** [comment]
It is starting to look pretty good, but not quite there yet.. I've fixed the 'back-face' problem my last comment.. as you can see in gif below, now i can see the back as it is rotated.. the problem was that I was calculating distance from the camera to the faces always from the same point.. now i rotate the camera with the object.. but for some reason, when viewing from sides I still can see through the object.. for example I can see the other arm through the body
![Recording 2023-12-25 at 17 02 42](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/f4e10fe6-cda2-46d9-93bb-f6feb1e3320e)


I made a lot of changes in the structure of the code, just to make it simpler to understand and work on. I also removed all tkinter stuff from the original project and control the movement, rotation and zoom with the mouse.. I changed almost nothing in the actual render code, just restructured it to make it simpler.(basically just put everything in a single file and remove all tkinter stuff).. so now when initializing the renderer, I just pass in the canvas handle and path to the .obj file, and then call render method.. everything else is up to the user(implementing buttons, colors, etc.) 

It would be pretty nice to have this package working correctly.. lightweight rendering without any openGL or anything, DIRECTLY in tkinter canvas.. more people should work on this .. I think it is an awesome project but I don't have enough experience to work on it alone

**Comment by Rad-hi** [comment]
I love the effort you are putting into this project, you are kinda making me want to go back to it and tinker with it a bit more.
To be clear, I am not a graphics engineer, neither do I have any experience with rendering/OpenGL, this project was just a fun idea that seemed interesting to pull off, so we're exploring together here !

I think what you should do is stop drawing the points that are occluded. Basically, you don't simply sort the faces' distances, and then render from furthest to closest. Instead, maybe you can pick each triangle that's supposed to be visible, and then remove the points that are within its area, but are further. This way you guarantee that nothing but what's supposed to be seen will be drawn (and this will make the application smoother since when I benchmarked the code, I found out that the drawing on the canvas was the bottleneck, not the math). I will look into your code when I can (I have a full time job now, can't do much during the week). Good luck, and again, this is humbling, and flattering, thank you !

**Comment by MarioGavran** [comment]
I think I'm getting there.. just have to guess right camera position and that should be it.. now, with what I am assuming is slightly off camera position, I am not rendering all polys that I should and I am rendering some polys that I shouldn't.. I guess if I get just right camera position it should render just right. 

I have changed the code a bit.. the biggest change is that as the object is rotated, new positions of vertices are saved in _vertices array, so the rotation angles are reset to 0,0,0 after every rotation.. I had to do this to avoid rotating the camera

![Recording 2023-12-27 at 15 12 49](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/ad899ef5-dac6-49ae-a11b-945a00dd740a)

**Comment by MarioGavran** [comment]
Simple cube is working pretty god now:
![Recording 2023-12-27 at 19 47 19](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/03661ef4-adb3-4515-8533-e8ec66ccb708)

But more complex shapes are still not there yet. I also now need z-buffering or ordering the faces because if there are two polygons one behind the other, and both are facing the camera, they can be rendered in wrong order(like monkeys eyebrows here) 
![Recording 2023-12-27 at 19 57 05](https://github.com/Rad-hi/3D-Rendering-Desktop-App/assets/46444307/7fd1eb09-6045-40e7-b5f5-f2285d6f064d)


Also, the MaleLow.obj model, where did it come from? because the vertices normals are weird in that file

**Comment by Rad-hi** [comment]
Looks cool, glad you're getting somewhere. About the `MaleLow.obj`, I downloaded it from a website that offers free 3D models, I am not sure what its name was tbh.

And yes, I think you're at the stage where you need Z buffering already.
